spring:
  application:
    name: ByteSchool
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/byteschool
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration
    default-schema: public

api:
  stripe:
    key: ${STRIPE_TEST_PUBLISHABLE_API_KEY}
    secret: ${STRIPE_TEST_SECRET_API_KEY}

