CREATE TABLE course
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date   date,
    end_date     date,
    name         VARCHAR(255),
    type         VARCHAR(255),
    slot         SMALLINT,
    max_capacity INTEGER                                  NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE course_current_students
(
    course_id           INTEGER NOT NULL,
    current_students_id INTEGER NOT NULL,
    CONSTRAINT pk_course_currentstudents PRIMARY KEY (course_id, current_students_id)
);

CREATE TABLE student
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE student_courses
(
    student_id INTEGER NOT NULL,
    courses_id INTEGER NOT NULL,
    CONSTRAINT pk_student_courses PRIMARY KEY (student_id, courses_id)
);

ALTER TABLE course_current_students
    ADD CONSTRAINT fk_coucurstu_on_course FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE course_current_students
    ADD CONSTRAINT fk_coucurstu_on_student FOREIGN KEY (current_students_id) REFERENCES student (id);

ALTER TABLE student_courses
    ADD CONSTRAINT fk_stucou_on_course FOREIGN KEY (courses_id) REFERENCES course (id);

ALTER TABLE student_courses
    ADD CONSTRAINT fk_stucou_on_student FOREIGN KEY (student_id) REFERENCES student (id);